// Generated by scripts/generate-daily-words.mjs from src/data/daily-puzzles.json and the MIT-licensed wordlist-english package, backed by SCOWL.
// Do not edit by hand; run npm run generate:daily-words.
// Generation fails unless source tiles and configured quartet words are unique, every tile has 2-4 letters, and each board has exactly the five configured four-tile paths with no extra valid quartet paths.

export const DAILY_PUZZLES = [
  {
    date: '2026-04-26',
    quartets: [["re","qu","ir","ed"],["equ","iv","al","ent"],["obj","ec","ti","on"],["ju","stif","ica","tion"],["mys","ter","io","us"]],
    words: ['alter', 'altered', 'entre', 'equal', 'equivalent', 'iron', 'ironed', 'justification', 'mys', 'mysterious', 'objection', 'onus', 'real', 'reed', 'required', 'retied', 'reused', 'tertial', 'tied', 'tire', 'used'],
  },
  {
    date: '2026-04-27',
    quartets: [["alt","ern","ativ","ely"],["rea","so","nab","ly"],["di","sap","pear","ing"],["imp","ort","an","ce"],["indi","ca","ti","on"]],
    words: ['alternatively', 'anon', 'anti', 'cadi', 'cation', 'ceca', 'cedi', 'dice', 'disappear', 'disappearing', 'imp', 'imply', 'implying', 'import', 'importance', 'importing', 'indication', 'lying', 'nab', 'once', 'only', 'ort', 'pear', 'pearly', 'readily', 'reasonably', 'sap', 'soon', 'tidily'],
  },
  {
    date: '2026-04-28',
    quartets: [["sign","ific","ant","ly"],["un","nece","ssar","ily"],["spe","cif","ica","lly"],["ir","ri","tat","es"],["av","ail","ab","le"]],
    words: ['able', 'ably', 'abri', 'ail', 'ant', 'antes', 'avail', 'available', 'irritates', 'leaves', 'lees', 'necessarily', 'riant', 'rile', 'sign', 'significant', 'significantly', 'specifically', 'tat', 'unable', 'unific', 'unnecessarily'],
  },
  {
    date: '2026-04-29',
    quartets: [["con","sequ","enc","es"],["di","sa","ppea","ring"],["ad","vi","si","ng"],["simu","lta","ne","ous"],["el","ect","ro","nic"]],
    words: ['adding', 'advising', 'con', 'cones', 'consequences', 'dies', 'diesel', 'dine', 'ding', 'dinges', 'disappearing', 'divine', 'diving', 'elect', 'electro', 'electronic', 'nevi', 'ousel', 'ring', 'road', 'roes', 'roving', 'sane', 'sang', 'sarong', 'saving', 'sequel', 'sequences', 'siding', 'simultaneous', 'sine', 'sing', 'singes', 'siring', 'vidicon', 'vies', 'vine', 'vinic', 'visa', 'vising'],
  },
  {
    date: '2026-04-30',
    quartets: [["se","ns","ib","le"],["app","ear","an","ce"],["si","gnif","ic","ance"],["ir","ri","ta","ted"],["con","trib","uti","ons"]],
    words: ['ancon', 'anear', 'anons', 'anta', 'anted', 'appear', 'appearance', 'apple', 'apprise', 'cerise', 'con', 'conic', 'conns', 'contributions', 'ear', 'earns', 'icons', 'irons', 'irritated', 'lean', 'lens', 'lesions', 'rice', 'rile', 'rise', 'sens', 'sensible', 'serins', 'significance', 'sins', 'sited', 'tace', 'tale', 'tans', 'ted', 'utile'],
  },
  {
    date: '2026-05-01',
    quartets: [["un","der","stan","ds"],["in","stit","ut","ion"],["exp","lan","ati","on"],["art","if","ic","ial"],["fa","mi","li","ar"]],
    words: ['art', 'artificial', 'deration', 'explanation', 'fader', 'fads', 'fain', 'familiar', 'faun', 'icon', 'inion', 'institution', 'ion', 'ionic', 'lan', 'lander', 'lands', 'liar', 'lids', 'lion', 'onion', 'stander', 'stands', 'under', 'understands', 'unific', 'union'],
  },
  {
    date: '2026-05-02',
    quartets: [["eve","ry","whe","re"],["ex","ec","ut","ed"],["au","tho","ri","ty"],["ass","oc","ia","te"],["sop","his","tic","ate"]],
    words: ['ass', 'associate', 'ate', 'aureate', 'authority', 'eve', 'every', 'everywhere', 'exec', 'executed', 'his', 'ocreate', 'reed', 'reeve', 'rete', 'rite', 'sop', 'sophistic', 'sophisticate', 'teed', 'tho', 'thorite', 'tic', 'where'],
  },
  {
    date: '2026-05-03',
    quartets: [["emb","arr","as","sing"],["ex","per","imen","tal"],["misu","nder","sto","od"],["re","li","gi","on"],["adv","ert","is","es"]],
    words: ['advert', 'advertises', 'advises', 'arras', 'arrases', 'arris', 'asper', 'aspersing', 'embarrassing', 'exert', 'exes', 'exon', 'experimental', 'lies', 'lion', 'lire', 'misunderstood', 'misusing', 'odes', 'ones', 'per', 'peris', 'reason', 'region', 'relies', 'religion', 'render', 'sing', 'singes', 'stogies', 'stood', 'store', 'talas', 'tales', 'tallies', 'talon'],
  },
  {
    date: '2026-05-04',
    quartets: [["ob","se","rvat","ion"],["imp","ort","ant","ly"],["ma","in","tai","ning"],["di","rec","to","ry"],["uns","ui","ta","ble"]],
    words: ['ant', 'dining', 'directory', 'imp', 'imply', 'import', 'important', 'importantly', 'inion', 'inly', 'inning', 'into', 'intoning', 'ion', 'lyse', 'main', 'mainly', 'maintaining', 'observation', 'obtain', 'obtaining', 'ort', 'recant', 'recto', 'rectory', 'table', 'tain', 'tamable', 'toning', 'unstable', 'unsuitable'],
  },
  {
    date: '2026-05-05',
    quartets: [["exp","er","ie","nced"],["apo","lo","gi","es"],["re","mo","te","ly"],["dis","co","ur","aged"],["cons","eq","uen","tly"]],
    words: ['aged', 'apologies', 'coly', 'conceder', 'concedes', 'cons', 'consequently', 'core', 'cote', 'courtly', 'dis', 'disco', 'discouraged', 'experienced', 'expertly', 'explore', 'gite', 'loco', 'logier', 'lore', 'lour', 'lyre', 'modiste', 'moly', 'more', 'mote', 'recons', 'rely', 'remote', 'remotely', 'rete', 'tees'],
  },
  {
    date: '2026-05-06',
    quartets: [["con","tin","ua","lly"],["doc","um","enti","ng"],["ap","pre","ci","ates"],["emb","ar","rass","ing"],["inc","omp","at","ible"]],
    words: ['aping', 'appreciates', 'arcing', 'arum', 'con', 'coning', 'continua', 'continually', 'doc', 'documenting', 'embarrass', 'embarrassing', 'enticing', 'incompatible', 'pre', 'tin'],
  },
  {
    date: '2026-05-07',
    quartets: [["int","rodu","ci","ng"],["ma","te","ri","als"],["ne","vert","hel","ess"],["intr","od","uct","ion"],["cat","eg","or","ies"]],
    words: ['cat', 'categories', 'cation', 'cine', 'cinema', 'cite', 'introducing', 'introduction', 'ion', 'macing', 'mane', 'marine', 'mate', 'materials', 'nevertheless', 'orals', 'rials', 'ricing', 'ring', 'rite', 'teals'],
  },
  {
    date: '2026-05-08',
    quartets: [["na","ti","on","al"],["su","pe","rvi","sor"],["di","sap","pea","ring"],["indi","vid","ua","lly"],["fa","ci","li","ty"]],
    words: ['cion', 'city', 'dial', 'dilly', 'disappearing', 'facial', 'facility', 'faring', 'individually', 'lion', 'livid', 'nape', 'nation', 'national', 'pea', 'peal', 'peaty', 'penally', 'peon', 'ring', 'sap', 'sully', 'supervisor', 'tiring', 'type'],
  },
  {
    date: '2026-05-09',
    quartets: [["comm","uni","cat","ion"],["rel","ig","io","us"],["re","la","ti","ve"],["ind","iv","idu","ally"],["po","ssib","ili","ty"]],
    words: ['ally', 'cat', 'cation', 'catty', 'communication', 'community', 'individually', 'ion', 'lati', 'lave', 'pore', 'possibility', 'really', 'relative', 'religion', 'religious', 'tire', 'typo', 'uni', 'unitive', 'unity', 'vela'],
  },
  {
    date: '2026-05-10',
    quartets: [["tec","hn","ol","ogy"],["unf","ort","un","ate"],["dem","oc","ra","tic"],["dis","adv","anta","ge"],["re","le","as","ed"]],
    words: ['advantage', 'advocate', 'anta', 'ate', 'democratic', 'dis', 'disadvantage', 'edge', 'geed', 'geology', 'leas', 'leased', 'ocreate', 'ology', 'ort', 'rage', 'rale', 'rare', 'reed', 'released', 'reticle', 'technology', 'tic', 'unfed', 'unfortunate'],
  },
  {
    date: '2026-05-11',
    quartets: [["co","mmu","ni","ty"],["rel","ig","io","us"],["op","por","tu","nity"],["mis","unde","rsto","od"],["dis","ap","pe","ar"]],
    words: ['appear', 'arty', 'community', 'coop', 'cope', 'dis', 'disappear', 'disco', 'misty', 'mistype', 'misunderstood', 'odious', 'opportunity', 'opus', 'pear', 'religious', 'type', 'understood'],
  },
  {
    date: '2026-05-12',
    quartets: [["pa","ra","ll","el"],["sig","nifi","can","tly"],["una","ccep","ta","ble"],["di","sapp","ea","ring"],["enc","our","ag","ing"]],
    words: ['can', 'caning', 'dill', 'disappearing', 'earing', 'eatable', 'encouraging', 'our', 'pall', 'palling', 'parable', 'parallel', 'paring', 'patly', 'raring', 'rata', 'ratable', 'ring', 'ringing', 'sapping', 'significantly', 'table', 'tael', 'tall', 'taring', 'unable', 'unacceptable'],
  },
  {
    date: '2026-05-13',
    quartets: [["au","di","en","ce"],["ar","tif","ici","al"],["opp","ort","unit","ies"],["in","fo","rmi","ng"],["es","tabl","ish","ed"]],
    words: ['alar', 'ales', 'ares', 'artificial', 'audial', 'audience', 'cedi', 'ceding', 'dial', 'diaries', 'dice', 'died', 'dies', 'ding', 'dinged', 'dinges', 'eddies', 'ending', 'establish', 'established', 'foal', 'foaled', 'foes', 'foin', 'forming', 'icing', 'indies', 'info', 'informing', 'opportunities', 'ort', 'tabled', 'tables', 'unit', 'united', 'unites', 'unities'],
  },
  {
    date: '2026-05-14',
    quartets: [["diff","icu","lti","es"],["dis","co","ur","age"],["exp","la","ini","ng"],["con","seq","uen","tly"],["di","stin","gu","ish"]],
    words: ['age', 'coding', 'coining', 'cola', 'con', 'cones', 'consequently', 'courage', 'courtly', 'dies', 'difficulties', 'ding', 'dinges', 'dis', 'disco', 'discourage', 'distingu', 'distinguish', 'explaining', 'gula', 'ladies', 'lading', 'langur', 'sequently'],
  },
  {
    date: '2026-05-15',
    quartets: [["re","li","ab","le"],["co","mpa","ra","ble"],["exp","eri","men","tal"],["ar","ith","met","ic"],["ma","in","ta","ins"]],
    words: ['able', 'arable', 'arithmetic', 'armet', 'blear', 'coble', 'coin', 'coins', 'cole', 'coli', 'coma', 'comet', 'comparable', 'compare', 'core', 'experimental', 'ins', 'instable', 'liable', 'liar', 'limen', 'lira', 'lire', 'main', 'mains', 'maintains', 'male', 'mara', 'mare', 'men', 'mental', 'met', 'metic', 'rain', 'rains', 'rale', 'ramen', 'rare', 'rata', 'ratable', 'ratal', 'rear', 'recoin', 'rein', 'reins', 'reliable', 'remain', 'remains', 'retable', 'retain', 'retains', 'table', 'taco', 'tain', 'tale', 'tali', 'tamable', 'tamale', 'tare'],
  },
  {
    date: '2026-05-16',
    quartets: [["ann","ounc","em","ent"],["ex","ce","ssi","ve"],["qu","al","if","ied"],["av","ai","lab","le"],["di","sco","ura","ging"]],
    words: ['alle', 'alleging', 'annal', 'annex', 'announcement', 'available', 'cedi', 'dial', 'dice', 'disco', 'discouraging', 'dive', 'excessive', 'lab', 'leal', 'quai', 'qualified', 'veal'],
  },
  {
    date: '2026-05-17',
    quartets: [["ann","ounc","em","ent"],["ex","ce","ssi","ve"],["qu","al","if","ied"],["av","ai","lab","le"],["di","sco","ura","ging"]],
    words: ['alle', 'alleging', 'annal', 'annex', 'announcement', 'available', 'cedi', 'dial', 'dice', 'disco', 'discouraging', 'dive', 'excessive', 'lab', 'leal', 'quai', 'qualified', 'veal'],
  },
  {
    date: '2026-05-18',
    quartets: [["pri","nc","ip","les"],["as","soc","ia","te"],["bea","ut","if","ul"],["re","so","ur","ces"],["comp","at","ibi","lity"]],
    words: ['associate', 'beaut', 'beautiful', 'compatibility', 'compre', 'prices', 'principles', 'reprices', 'resoles', 'resources', 'rete', 'sociality', 'socles', 'soles', 'sore', 'soul', 'sour', 'sources', 'teas', 'teat'],
  },
  {
    date: '2026-05-19',
    quartets: [["dem","oc","ra","tic"],["re","la","ti","on"],["in","adeq","ua","te"],["expe","ri","en","ces"],["opp","ort","uni","ties"]],
    words: ['adequate', 'democratic', 'demon', 'enlaces', 'entices', 'entire', 'entities', 'experiences', 'inadequate', 'inti', 'laces', 'lain', 'lari', 'late', 'lateen', 'lati', 'latices', 'ontic', 'opportunities', 'ort', 'races', 'rain', 'rare', 'rarities', 'rate', 'ration', 'rein', 'relate', 'relation', 'rete', 'reties', 'reunion', 'reunite', 'rices', 'rite', 'teen', 'tic', 'ties', 'tire', 'uni', 'union', 'unite', 'unities'],
  },
  {
    date: '2026-05-20',
    quartets: [["re","gu","la","rly"],["ri","di","culo","us"],["su","ppo","sed","ly"],["con","si","de","ring"],["intr","od","uc","ed"]],
    words: ['con', 'coned', 'considering', 'deed', 'desire', 'desiring', 'deuced', 'died', 'dire', 'direly', 'disused', 'gula', 'introduced', 'lade', 'lari', 'lyre', 'recon', 'rede', 'reed', 'regularly', 'rely', 'reside', 'reused', 'ride', 'ridiculous', 'ring', 'ringed', 'ringside', 'seduced', 'side', 'sire', 'siring', 'sued', 'supposed', 'supposedly', 'sure', 'surely', 'surly', 'used'],
  },
  {
    date: '2026-05-21',
    quartets: [["ar","ran","gem","ent"],["ne","cess","ari","ly"],["en","cou","ra","ge"],["com","mu","ni","ty"],["emb","arr","as","ses"]],
    words: ['arenas', 'arias', 'arises', 'arrange', 'arrangement', 'arras', 'arrases', 'arty', 'asses', 'cess', 'comas', 'commune', 'community', 'courage', 'embarrasses', 'encourage', 'enrage', 'gear', 'gem', 'gene', 'genera', 'geneses', 'lyses', 'murage', 'muses', 'near', 'nearly', 'necessarily', 'nine', 'ninety', 'rage', 'ran', 'range'],
  },
  {
    date: '2026-05-22',
    quartets: [["am","big","uo","us"],["dir","ec","to","ry"],["ar","it","hmet","ic"],["ex","ces","si","ve"],["acc","iden","ta","lly"]],
    words: ['accidences', 'accidentally', 'ambiguous', 'arithmetic', 'big', 'cesta', 'directory', 'exam', 'excessive', 'exec', 'exit', 'silly', 'tally', 'taus', 'tolly', 'totally', 'very', 'veto'],
  },
  {
    date: '2026-05-23',
    quartets: [["em","ba","rras","ses"],["inc","ompa","tib","le"],["ind","ivi","du","al"],["dir","ec","tio","ns"],["dis","cour","ag","ing"]],
    words: ['alba', 'alle', 'bale', 'bans', 'bases', 'courses', 'directions', 'dis', 'discouraging', 'discourses', 'dual', 'duns', 'durras', 'embarrasses', 'incompatible', 'individual', 'ingle', 'leal', 'lens', 'lensing'],
  },
  {
    date: '2026-05-24',
    quartets: [["int","ern","ati","onal"],["ma","gni","tu","de"],["ex","is","ten","ce"],["dis","cou","ra","ging"],["co","mpla","in","ed"]],
    words: ['cede', 'cedis', 'coati', 'code', 'coed', 'coin', 'coined', 'coma', 'complain', 'complained', 'complaint', 'deco', 'deed', 'dis', 'disco', 'discoed', 'discouraging', 'edging', 'exceed', 'exedra', 'existence', 'indeed', 'intern', 'international', 'interned', 'intis', 'mace', 'made', 'magnitude', 'main', 'mara', 'race', 'raging', 'rain', 'rained', 'raised', 'raisin', 'ten', 'tude', 'tuis', 'turaco'],
  },
  {
    date: '2026-05-25',
    quartets: [["fa","mi","li","ar"],["und","ergr","adua","te"],["co","nse","quen","ce"],["pos","sib","ilit","ies"],["pu","rc","ha","se"]],
    words: ['arte', 'cense', 'coarse', 'coli', 'consequence', 'cote', 'face', 'familiar', 'fate', 'haar', 'halite', 'hate', 'liar', 'lice', 'license', 'lite', 'mice', 'mite', 'posies', 'posse', 'possibilities', 'puce', 'puli', 'pumice', 'purchase', 'sear', 'semi', 'sense', 'sequence', 'sib', 'tear', 'tense', 'undergraduate', 'undies'],
  },
  {
    date: '2026-05-26',
    quartets: [["ab","ili","ti","es"],["re","pe","at","ing"],["diff","ic","ult","ies"],["in","te","rpr","ets"],["dis","cip","li","ne"]],
    words: ['abates', 'abating', 'abets', 'abies', 'abilities', 'attire', 'difficult', 'difficulties', 'dis', 'discipline', 'ices', 'icing', 'inline', 'interprets', 'inti', 'intine', 'lies', 'line', 'lire', 'lite', 'neat', 'peat', 'pees', 'pelite', 'petite', 'recipes', 'rein', 'reining', 'relies', 'reline', 'repeat', 'repeating', 'rete', 'retene', 'reties', 'teat', 'tees', 'tepees', 'ties', 'tine', 'tire'],
  },
  {
    date: '2026-05-27',
    quartets: [["un","ive","rsi","ty"],["sig","nifi","ca","ntly"],["op","por","tun","ity"],["cons","equ","ent","ly"],["ex","er","ci","se"]],
    words: ['case', 'city', 'cons', 'consent', 'consequent', 'consequently', 'enter', 'entity', 'equity', 'excise', 'exercise', 'lyse', 'opportunity', 'seer', 'significantly', 'signifier', 'tun', 'tuner', 'unity', 'university'],
  },
  {
    date: '2026-05-28',
    quartets: [["im","medi","ate","ly"],["rel","ig","io","us"],["cir","cu","msta","nce"],["soph","is","tica","tes"],["nec","es","si","ty"]],
    words: ['ate', 'cir', 'circumstance', 'cues', 'immediate', 'immediately', 'mediate', 'mediately', 'medius', 'necessity', 'relate', 'religious', 'since', 'sites', 'sophisticates', 'testy', 'uses'],
  },
  {
    date: '2026-05-29',
    quartets: [["li","ke","wi","se"],["in","vis","ib","le"],["art","if","ic","ial"],["ri","dic","ul","ous"],["con","tri","bu","te"]],
    words: ['art', 'article', 'artificial', 'con', 'conic', 'conte', 'contribute', 'contrite', 'invisible', 'like', 'likewise', 'lite', 'ridiculous', 'rile', 'rise', 'rite', 'serious', 'tribute', 'trike', 'trite', 'visible', 'wile', 'wise', 'wite'],
  },
  {
    date: '2026-05-30',
    quartets: [["em","ba","rras","sed"],["circ","um","stan","ces"],["su","pe","ri","or"],["ind","iv","idu","al"],["te","chno","lo","gy"]],
    words: ['alba', 'alum', 'barite', 'barium', 'based', 'bate', 'circumstances', 'embarrassed', 'individual', 'lobate', 'logy', 'lope', 'oral', 'orgy', 'peal', 'peba', 'peri', 'rial', 'rices', 'ripe', 'rite', 'sedgy', 'sedum', 'stances', 'superior', 'teal', 'techno', 'technology', 'teem'],
  },
  {
    date: '2026-05-31',
    quartets: [["au","to","mob","ile"],["me","anin","gle","ss"],["su","pe","ri","or"],["op","po","sit","ion"],["in","conv","eni","ence"]],
    words: ['auto', 'automobile', 'convenience', 'inconvenience', 'ingle', 'inion', 'into', 'ion', 'meaningless', 'mess', 'mob', 'mobile', 'opinion', 'opposition', 'peri', 'pome', 'poop', 'poor', 'pope', 'posit', 'position', 'rime', 'ripe', 'sit', 'superior', 'suss', 'toile', 'tome', 'tope', 'tori', 'toss'],
  },
  {
    date: '2026-06-01',
    quartets: [["in","tern","ati","onal"],["dis","co","veri","ng"],["unfo","rtu","nate","ly"],["so","lu","ti","ons"],["con","seq","uen","ce"]],
    words: ['cedis', 'coati', 'coating', 'coin', 'coly', 'con', 'connate', 'consequence', 'coons', 'covering', 'dis', 'disco', 'discovering', 'inly', 'innate', 'innately', 'intern', 'international', 'inti', 'luce', 'lunate', 'lung', 'luting', 'sequence', 'solutions', 'song', 'tern', 'ting', 'tingly', 'unfortunate', 'unfortunately', 'verily'],
  },
  {
    date: '2026-06-02',
    quartets: [["pe","cu","li","ar"],["ins","ti","tut","ions"],["com","mer","ci","al"],["re","pea","te","dly"],["rec","omm","en","ded"]],
    words: ['alar', 'arte', 'cite', 'commercial', 'compete', 'cure', 'cute', 'ended', 'entire', 'ins', 'institutions', 'ions', 'liar', 'lien', 'lire', 'lite', 'pea', 'peal', 'pear', 'peculiar', 'peen', 'pelite', 'petite', 'real', 'rear', 'recipe', 'recite', 'recommended', 'recti', 'redly', 'reins', 'repeal', 'repeatedly', 'rete', 'teal', 'tear', 'teen', 'tided', 'timer', 'tire', 'tiredly', 'tut', 'tutti'],
  },
  {
    date: '2026-06-03',
    quartets: [["av","ail","ab","le"],["soph","ist","ica","ted"],["im","agi","nat","ion"],["spe","ci","fic","ally"],["po","we","rf","ul"]],
    words: ['able', 'ableist', 'agile', 'ail', 'ally', 'avail', 'available', 'avion', 'cited', 'imagination', 'ion', 'istle', 'nation', 'nationally', 'pole', 'powerful', 'sophist', 'sophisticated', 'specially', 'specific', 'specifically', 'ted'],
  },
  {
    date: '2026-06-04',
    quartets: [["fa","mi","li","ar"],["int","ell","igen","ce"],["pa","rag","ra","ph"],["de","fin","iti","ve"],["app","rop","ria","te"]],
    words: ['appropriate', 'arte', 'cede', 'cerate', 'ceria', 'dear', 'deface', 'definitive', 'deli', 'ell', 'face', 'fade', 'faint', 'familiar', 'fate', 'fave', 'fin', 'intelligence', 'liar', 'lice', 'lira', 'lite', 'live', 'mice', 'mite', 'pace', 'paint', 'parade', 'paragraph', 'paraph', 'pate', 'pave', 'race', 'rag', 'rate', 'rave', 'ria', 'tear', 'tephra'],
  },
  {
    date: '2026-06-05',
    quartets: [["suf","fi","cie","ntly"],["unr","eas","ona","ble"],["sig","nif","ican","ce"],["va","ca","ti","ons"],["fu","nda","me","ntal"]],
    words: ['cable', 'came', 'cations', 'ceca', 'cental', 'findable', 'fume', 'fundamental', 'mendable', 'mental', 'significance', 'suffice', 'sufficiently', 'time', 'unreasonable', 'unreasons', 'vacantly', 'vacations', 'vanda'],
  },
  {
    date: '2026-06-06',
    quartets: [["int","rod","uc","es"],["phe","no","me","non"],["ca","pa","ci","ty"],["pre","par","ati","on"],["inci","dent","al","ly"]],
    words: ['ales', 'ally', 'alpaca', 'cadent', 'came', 'canoes', 'canon', 'capacity', 'cion', 'city', 'dent', 'dental', 'dentally', 'dentation', 'incident', 'incidental', 'incidentally', 'intones', 'introduces', 'meal', 'noes', 'non', 'nones', 'noon', 'ones', 'only', 'paint', 'paly', 'par', 'pares', 'party', 'phenomenon', 'pheon', 'pre', 'preparation', 'prepares', 'rod'],
  },
  {
    date: '2026-06-07',
    quartets: [["in","tr","odu","ce"],["del","ibe","ra","tely"],["unre","as","ona","ble"],["dis","co","ver","ed"],["au","tom","ob","ile"]],
    words: ['aura', 'automobile', 'bleed', 'ceased', 'cedis', 'coble', 'coed', 'coin', 'coined', 'cover', 'covered', 'deliberately', 'delver', 'dis', 'disco', 'discoed', 'discover', 'discovered', 'introduce', 'race', 'rain', 'rained', 'raver', 'tom', 'tribe', 'trona', 'unreasonable'],
  },
  {
    date: '2026-06-08',
    quartets: [["be","aut","if","ul"],["pe","rfo","rm","ance"],["oc","ca","sion","ally"],["re","qu","ire","ment"],["in","div","id","uals"]],
    words: ['ally', 'beaut', 'beautiful', 'berm', 'cain', 'cape', 'care', 'caul', 'divulsion', 'individuals', 'ire', 'mentally', 'occasion', 'occasionally', 'perform', 'performance', 'perm', 'quid', 'quin', 'quire', 'really', 'rein', 'require', 'requirement'],
  },
  {
    date: '2026-06-09',
    quartets: [["occ","as","io","nal"],["re","le","van","ce"],["ec","on","om","ic"],["co","mpat","ibil","ity"],["ind","iv","id","ual"]],
    words: ['cole', 'compatibility', 'coom', 'coon', 'core', 'economic', 'icon', 'idle', 'individual', 'leas', 'occasional', 'once', 'reason', 'relevance', 'renal', 'van', 'vanity'],
  },
  {
    date: '2026-06-10',
    quartets: [["prog","ra","mm","ers"],["va","ri","ab","les"],["rel","ati","onsh","ip"],["comp","reh","ens","ive"],["de","fin","iti","ve"]],
    words: ['abrade', 'abri', 'comprehensive', 'definers', 'definitive', 'derive', 'ens', 'fin', 'programmers', 'rales', 'rammers', 'rave', 'rehab', 'relationship', 'relative', 'relive', 'ride', 'riles', 'rive', 'vales', 'vara', 'variables', 'veers'],
  },
  {
    date: '2026-06-11',
    quartets: [["ye","ste","rd","ay"],["rid","ic","ulo","us"],["ap","pea","ra","nce"],["au","di","en","ce"],["dif","fic","ul","ties"]],
    words: ['appearance', 'audience', 'aura', 'cedi', 'dice', 'difficulties', 'ficus', 'pea', 'peace', 'race', 'radius', 'rance', 'rid', 'ridiculous', 'ties', 'yesterday'],
  },
  {
    date: '2026-06-12',
    quartets: [["mu","lt","ip","le"],["ind","iv","idu","als"],["in","co","mpat","ible"],["the","or","et","ical"],["poss","ibi","lit","ies"]],
    words: ['coals', 'coin', 'cole', 'colt', 'compatible', 'incompatible', 'indies', 'individuals', 'ivies', 'ivories', 'leet', 'lethe', 'lit', 'mule', 'multiple', 'orals', 'orle', 'posset', 'possibilities', 'possible', 'the', 'theoretical', 'theories'],
  },
  {
    date: '2026-06-13',
    quartets: [["co","mmu","nica","te"],["di","sa","ppe","ared"],["ci","rcu","msta","nce"],["ev","id","en","ce"],["pr","oc","ess","ed"]],
    words: ['cedi', 'circumstance', 'cite', 'coed', 'communicate', 'commute', 'cote', 'dice', 'died', 'disappeared', 'essence', 'even', 'evened', 'evidence', 'press', 'pressed', 'prided', 'process', 'processed', 'said', 'sance', 'sate', 'sateen', 'teared', 'teed', 'teen'],
  },
  {
    date: '2026-06-14',
    quartets: [["rea","son","ab","ly"],["su","pe","ri","or"],["imp","rov","em","ents"],["sig","ni","fica","nce"],["oc","ca","si","on"]],
    words: ['ably', 'abri', 'cape', 'imp', 'imply', 'imprison', 'improvements', 'nisi', 'occasion', 'ocrea', 'only', 'orca', 'pence', 'peon', 'peri', 'reason', 'reasonably', 'ripe', 'ripely', 'significance', 'since', 'son', 'sonly', 'superior'],
  },
  {
    date: '2026-06-15',
    quartets: [["bro","adc","as","ting"],["add","it","io","nal"],["sup","erv","is","or"],["de","fi","nit","ive"],["re","li","gi","on"]],
    words: ['add', 'additional', 'additive', 'broadcasting', 'definitive', 'deli', 'final', 'fire', 'lion', 'lire', 'nit', 'orison', 'reason', 'rede', 'region', 'reive', 'religion', 'renal', 'sup', 'supervisor', 'ting'],
  },
] as const
