// Generated by scripts/generate-daily-words.mjs from src/data/daily-puzzles.json and the MIT-licensed wordlist-english package, backed by SCOWL.
// Do not edit by hand; run npm run generate:daily-words.
// Generation fails unless source tiles are unique, every tile has 2-4 letters, and each board has exactly the five target four-tile words with no extra valid quartets.

export const DAILY_PUZZLES = [
  {
    date: '2026-04-26',
    quartets: [["re","qu","ir","ed"],["equ","iv","al","ent"],["obj","ec","ti","on"],["ju","stif","ica","tion"],["mys","ter","io","us"]],
    words: ['alter', 'altered', 'entre', 'equal', 'equivalent', 'iron', 'ironed', 'justification', 'mys', 'mysterious', 'objection', 'onus', 'real', 'reed', 'required', 'retied', 'reused', 'tertial', 'tied', 'tire', 'used'],
  },
  {
    date: '2026-04-27',
    quartets: [["alt","ern","ativ","ely"],["rea","so","nab","ly"],["di","sap","pear","ing"],["imp","ort","an","ce"],["indi","ca","ti","on"]],
    words: ['alternatively', 'anon', 'anti', 'cadi', 'cation', 'ceca', 'cedi', 'dice', 'disappear', 'disappearing', 'imp', 'imply', 'implying', 'import', 'importance', 'importing', 'indication', 'lying', 'nab', 'once', 'only', 'ort', 'pear', 'pearly', 'readily', 'reasonably', 'sap', 'soon', 'tidily'],
  },
  {
    date: '2026-04-28',
    quartets: [["sign","ific","ant","ly"],["un","nece","ssar","ily"],["spe","cif","ica","lly"],["ir","ri","tat","es"],["av","ail","ab","le"]],
    words: ['able', 'ably', 'abri', 'ail', 'ant', 'antes', 'avail', 'available', 'irritates', 'leaves', 'lees', 'necessarily', 'riant', 'rile', 'sign', 'significant', 'significantly', 'specifically', 'tat', 'unable', 'unific', 'unnecessarily'],
  },
  {
    date: '2026-04-29',
    quartets: [["con","sequ","enc","es"],["di","sa","ppea","ring"],["ad","vi","si","ng"],["simu","lta","ne","ous"],["el","ect","ro","nic"]],
    words: ['adding', 'advising', 'con', 'cones', 'consequences', 'dies', 'diesel', 'dine', 'ding', 'dinges', 'disappearing', 'divine', 'diving', 'elect', 'electro', 'electronic', 'nevi', 'ousel', 'ring', 'road', 'roes', 'roving', 'sane', 'sang', 'sarong', 'saving', 'sequel', 'sequences', 'siding', 'simultaneous', 'sine', 'sing', 'singes', 'siring', 'vidicon', 'vies', 'vine', 'vinic', 'visa', 'vising'],
  },
  {
    date: '2026-04-30',
    quartets: [["se","ns","ib","le"],["app","ear","an","ce"],["si","gnif","ic","ance"],["ir","ri","ta","ted"],["con","trib","uti","ons"]],
    words: ['ancon', 'anear', 'anons', 'anta', 'anted', 'appear', 'appearance', 'apple', 'apprise', 'cerise', 'con', 'conic', 'conns', 'contributions', 'ear', 'earns', 'icons', 'irons', 'irritated', 'lean', 'lens', 'lesions', 'rice', 'rile', 'rise', 'sens', 'sensible', 'serins', 'significance', 'sins', 'sited', 'tace', 'tale', 'tans', 'ted', 'utile'],
  },
  {
    date: '2026-05-01',
    quartets: [["un","der","stan","ds"],["in","stit","ut","ion"],["exp","lan","ati","on"],["art","if","ic","ial"],["fa","mi","li","ar"]],
    words: ['art', 'artificial', 'deration', 'explanation', 'fader', 'fads', 'fain', 'familiar', 'faun', 'icon', 'inion', 'institution', 'ion', 'ionic', 'lan', 'lander', 'lands', 'liar', 'lids', 'lion', 'onion', 'stander', 'stands', 'under', 'understands', 'unific', 'union'],
  },
  {
    date: '2026-05-02',
    quartets: [["eve","ry","whe","re"],["ex","ec","ut","ed"],["au","tho","ri","ty"],["ass","oc","ia","te"],["sop","his","tic","ate"]],
    words: ['ass', 'associate', 'ate', 'aureate', 'authority', 'eve', 'every', 'everywhere', 'exec', 'executed', 'his', 'ocreate', 'reed', 'reeve', 'rete', 'rite', 'sop', 'sophistic', 'sophisticate', 'teed', 'tho', 'thorite', 'tic', 'where'],
  },
  {
    date: '2026-05-03',
    quartets: [["emb","arr","as","sing"],["ex","per","imen","tal"],["misu","nder","sto","od"],["re","li","gi","on"],["adv","ert","is","es"]],
    words: ['advert', 'advertises', 'advises', 'arras', 'arrases', 'arris', 'asper', 'aspersing', 'embarrassing', 'exert', 'exes', 'exon', 'experimental', 'lies', 'lion', 'lire', 'misunderstood', 'misusing', 'odes', 'ones', 'per', 'peris', 'reason', 'region', 'relies', 'religion', 'render', 'sing', 'singes', 'stogies', 'stood', 'store', 'talas', 'tales', 'tallies', 'talon'],
  },
  {
    date: '2026-05-04',
    quartets: [["ob","se","rvat","ion"],["imp","ort","ant","ly"],["ma","in","tai","ning"],["di","rec","to","ry"],["uns","ui","ta","ble"]],
    words: ['ant', 'dining', 'directory', 'imp', 'imply', 'import', 'important', 'importantly', 'inion', 'inly', 'inning', 'into', 'intoning', 'ion', 'lyse', 'main', 'mainly', 'maintaining', 'observation', 'obtain', 'obtaining', 'ort', 'recant', 'recto', 'rectory', 'table', 'tain', 'tamable', 'toning', 'unstable', 'unsuitable'],
  },
  {
    date: '2026-05-05',
    quartets: [["exp","er","ie","nced"],["apo","lo","gi","es"],["re","mo","te","ly"],["dis","co","ur","aged"],["cons","eq","uen","tly"]],
    words: ['aged', 'apologies', 'coly', 'conceder', 'concedes', 'cons', 'consequently', 'core', 'cote', 'courtly', 'dis', 'disco', 'discouraged', 'experienced', 'expertly', 'explore', 'gite', 'loco', 'logier', 'lore', 'lour', 'lyre', 'modiste', 'moly', 'more', 'mote', 'recons', 'rely', 'remote', 'remotely', 'rete', 'tees'],
  },
  {
    date: '2026-05-06',
    quartets: [["con","tin","ua","lly"],["doc","um","enti","ng"],["ap","pre","ci","ates"],["emb","ar","rass","ing"],["inc","omp","at","ible"]],
    words: ['aping', 'appreciates', 'arcing', 'arum', 'con', 'coning', 'continua', 'continually', 'doc', 'documenting', 'embarrass', 'embarrassing', 'enticing', 'incompatible', 'pre', 'tin'],
  },
  {
    date: '2026-05-07',
    quartets: [["int","rodu","ci","ng"],["ma","te","ri","als"],["ne","vert","hel","ess"],["intr","od","uct","ion"],["cat","eg","or","ies"]],
    words: ['cat', 'categories', 'cation', 'cine', 'cinema', 'cite', 'introducing', 'introduction', 'ion', 'macing', 'mane', 'marine', 'mate', 'materials', 'nevertheless', 'orals', 'rials', 'ricing', 'ring', 'rite', 'teals'],
  },
  {
    date: '2026-05-08',
    quartets: [["na","ti","on","al"],["su","pe","rvi","sor"],["di","sap","pea","ring"],["indi","vid","ua","lly"],["fa","ci","li","ty"]],
    words: ['cion', 'city', 'dial', 'dilly', 'disappearing', 'facial', 'facility', 'faring', 'individually', 'lion', 'livid', 'nape', 'nation', 'national', 'pea', 'peal', 'peaty', 'penally', 'peon', 'ring', 'sap', 'sully', 'supervisor', 'tiring', 'type'],
  },
  {
    date: '2026-05-09',
    quartets: [["comm","uni","cat","ion"],["rel","ig","io","us"],["re","la","ti","ve"],["ind","iv","idu","ally"],["po","ssib","ili","ty"]],
    words: ['ally', 'cat', 'cation', 'catty', 'communication', 'community', 'individually', 'ion', 'lati', 'lave', 'pore', 'possibility', 'really', 'relative', 'religion', 'religious', 'tire', 'typo', 'uni', 'unitive', 'unity', 'vela'],
  },
  {
    date: '2026-05-10',
    quartets: [["tec","hn","ol","ogy"],["unf","ort","un","ate"],["dem","oc","ra","tic"],["dis","adv","anta","ge"],["re","le","as","ed"]],
    words: ['advantage', 'advocate', 'anta', 'ate', 'democratic', 'dis', 'disadvantage', 'edge', 'geed', 'geology', 'leas', 'leased', 'ocreate', 'ology', 'ort', 'rage', 'rale', 'rare', 'reed', 'released', 'reticle', 'technology', 'tic', 'unfed', 'unfortunate'],
  },
  {
    date: '2026-05-11',
    quartets: [["co","mmu","ni","ty"],["rel","ig","io","us"],["op","por","tu","nity"],["mis","unde","rsto","od"],["dis","ap","pe","ar"]],
    words: ['appear', 'arty', 'community', 'coop', 'cope', 'dis', 'disappear', 'disco', 'misty', 'mistype', 'misunderstood', 'odious', 'opportunity', 'opus', 'pear', 'religious', 'type', 'understood'],
  },
  {
    date: '2026-05-12',
    quartets: [["pa","ra","ll","el"],["sig","nifi","can","tly"],["una","ccep","ta","ble"],["di","sapp","ea","ring"],["enc","our","ag","ing"]],
    words: ['can', 'caning', 'dill', 'disappearing', 'earing', 'eatable', 'encouraging', 'our', 'pall', 'palling', 'parable', 'parallel', 'paring', 'patly', 'raring', 'rata', 'ratable', 'ring', 'ringing', 'sapping', 'significantly', 'table', 'tael', 'tall', 'taring', 'unable', 'unacceptable'],
  },
  {
    date: '2026-05-13',
    quartets: [["au","di","en","ce"],["ar","tif","ici","al"],["opp","ort","unit","ies"],["in","fo","rmi","ng"],["es","tabl","ish","ed"]],
    words: ['alar', 'ales', 'ares', 'artificial', 'audial', 'audience', 'cedi', 'ceding', 'dial', 'diaries', 'dice', 'died', 'dies', 'ding', 'dinged', 'dinges', 'eddies', 'ending', 'establish', 'established', 'foal', 'foaled', 'foes', 'foin', 'forming', 'icing', 'indies', 'info', 'informing', 'opportunities', 'ort', 'tabled', 'tables', 'unit', 'united', 'unites', 'unities'],
  },
  {
    date: '2026-05-14',
    quartets: [["diff","icu","lti","es"],["dis","co","ur","age"],["exp","la","ini","ng"],["con","seq","uen","tly"],["di","stin","gu","ish"]],
    words: ['age', 'coding', 'coining', 'cola', 'con', 'cones', 'consequently', 'courage', 'courtly', 'dies', 'difficulties', 'ding', 'dinges', 'dis', 'disco', 'discourage', 'distingu', 'distinguish', 'explaining', 'gula', 'ladies', 'lading', 'langur', 'sequently'],
  },
  {
    date: '2026-05-15',
    quartets: [["re","li","ab","le"],["co","mpa","ra","ble"],["exp","eri","men","tal"],["ar","ith","met","ic"],["ma","in","ta","ins"]],
    words: ['able', 'arable', 'arithmetic', 'armet', 'blear', 'coble', 'coin', 'coins', 'cole', 'coli', 'coma', 'comet', 'comparable', 'compare', 'core', 'experimental', 'ins', 'instable', 'liable', 'liar', 'limen', 'lira', 'lire', 'main', 'mains', 'maintains', 'male', 'mara', 'mare', 'men', 'mental', 'met', 'metic', 'rain', 'rains', 'rale', 'ramen', 'rare', 'rata', 'ratable', 'ratal', 'rear', 'recoin', 'rein', 'reins', 'reliable', 'remain', 'remains', 'retable', 'retain', 'retains', 'table', 'taco', 'tain', 'tale', 'tali', 'tamable', 'tamale', 'tare'],
  },
] as const
